import { StringField } from '../base/string-field';
import type { EmptyConfig } from '../base/types';

type PrFooterConfigKey = 'prFooter';
type PrFooterConfigValue = string;

export class PrFooterField<T extends EmptyConfig> extends StringField<
  T,
  PrFooterConfigKey,
  PrFooterConfigValue
> {
  override name = 'prFooter' as const;

  override description =
    'Text added here will be placed last in the PR body, with a divider separator before it.';

  override defaultValue =
    'This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).' as const;
}
